language: python

dist: xenial
python:
  - "3.6"

env:
  global:
    - MOZ_HEADLESS=1

addons: # get google-chrome-stable for selernium testing
  firefox: latest

cache:
  pip: true

# Ensure pre-requisite of psycopg2 Python package is installed
before_install:
  - sudo apt-get install -y libpq-dev

# Install dependencies
install:
  - wget https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview --yes
  - poetry install -E pgsql -E gunicorn
  # Install GeckoDriver (for firefox)
  - curl -sSL https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz | sudo tar -zx -C /usr/local/share
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
  
# Run tests and capture coverage stats
script:
  - poetry run coverage run manage.py test

# Push those stats to codecov.io
after_success:
  - codecov
